01 html structure
xsenikx/P2-reservia pull request #10
Opened 2020-12-09 00:06 UTC by xsenikx

bonjour wyona, voilà j'ai fait les modifications du fichier:
-changement de nom du fichier
- ajout des méta 
et dans le body la structure demandé

dit moi, si c'est bon pour toi ?

2020-12-09 06:58 UTC, Tutt-J requested changes
See my comments and please indent HTML

2020-12-09 06:58 UTC, Tutt-J commented on index.html
> +  <meta name="description" content="Projet-2 'Réservia' hébergement et activité en France">
Please put a reak description like "Réservia, le logement de vos rêves à porter de clics"

2020-12-09 06:58 UTC, Tutt-J commented on index.html
> +  <meta name="keywords" content="HTML, CSS">
No needed, Google not use this

2020-12-09 09:45 UTC, xsenikx commented
j'ai enlever le "keyword" et modifier ma description c'est okey pour toi ?

2020-12-09 21:25 UTC, xsenikx commented
J'ai indenter pour que mon code soit propre merci normalement ça doit être bon

2020-12-10 09:00 UTC, Tutt-J approved these changes

2020-12-10 09:28 UTC, merged