Ajout de la nav
xsenikx/P2-reservia pull request #14
Opened 2020-12-11 09:52 UTC by xsenikx

Ajout de la Nav vérification S'il te plait

2020-12-11 10:46 UTC, Tutt-J reviewed
View my comments and put it out of header in a section with id seach_bar for example

2020-12-11 10:46 UTC, Tutt-J commented on index.html
> +          <input type="text" name="location" value="Marseille,France">
Missing  method

2020-12-11 10:46 UTC, Tutt-J commented on index.html
> +          <button>Rechercher</button>
Must be input type submit

2020-12-11 10:46 UTC, Tutt-J commented on index.html
> +          <input type="text" name="location" value="Marseille,France">
Missing label

2020-12-11 10:46 UTC, Tutt-J commented on index.html
> +        <h3 class="small">
Why h3 ? No class at this moment...

2020-12-12 09:16 UTC, Tutt-J requested changes

2020-12-12 09:16 UTC, Tutt-J commented on index.html
> +          <label for="Localistion">
localisAtion for and name

2020-12-12 09:16 UTC, Tutt-J commented on index.html
> +        <form action="#">
missing method

2020-12-12 09:16 UTC, Tutt-J commented on index.html
> +          <input type="submit" name="Localistion" value="Marseille,France">
Missing id="localisation"

2020-12-12 09:16 UTC, Tutt-J commented on index.html
> +        <h3>
Must be h1 or h2

2020-12-12 09:16 UTC, Tutt-J commented on index.html
> +        </form>
Must be inside a section with id="search_bar"

2020-12-15 04:10 UTC, xsenikx commented
Fermeture de la pull request et réouverture sur la nouvelle branch

2020-12-15 09:20 UTC, closed without merging