Ajout de l'hébergement
xsenikx/P2-reservia pull request #17
Opened 2020-12-16 09:44 UTC by xsenikx

Voici ma partie sur l'hébergement, j'utilise les divs seulement pour travailler sur ma disposition 

Dit-moi ce qui ne va pas en ce qui concerne cette partie 

Merci

2020-12-16 09:50 UTC, Tutt-J requested changes

2020-12-16 09:50 UTC, Tutt-J commented on index.html
> +         <section id="Layout">
if must no use maj !! And maybe better to use id="accommodation"

2020-12-16 09:50 UTC, Tutt-J commented on index.html
> +          <div id="offer">
Remove this div

2020-12-16 09:50 UTC, Tutt-J commented on index.html
> +            <div id="offer_grid">
Removet his div and use foreach accomodation an <article>

2020-12-17 05:33 UTC, xsenikx commented
Réamenagement de la page pour une lecture plus lisible du HTML sans de modification , en attente pour la partie Hébergement

2020-12-17 08:33 UTC, Tutt-J approved these changes

2020-12-17 09:38 UTC, merged