Ajout de la big section pour hébergement et populaire
xsenikx/P2-reservia pull request #28
Opened 2020-12-20 09:14 UTC by xsenikx

W3C n'approuve pas la méthode aurais-tu une suggestion a me donner

2020-12-20 22:49 UTC, xsenikx commented
Changement d'élément au lieu d'une section pour le "layout"

je l'ai remplacer par une div en attente pour la merge merci

2020-12-21 16:28 UTC, Tutt-J requested changes

2020-12-21 16:28 UTC, Tutt-J commented on index.html
> +      <div id="layout">
remove this id

2020-12-22 10:10 UTC, Tutt-J approved these changes

2020-12-22 10:11 UTC, merged