01 html structure
xsenikx/P2-reservia pull request #9
Opened 2020-11-19 05:51 UTC by xsenikx

Bonjour Wyona,

Dit-moi si pour toi la structure est correct 

Merci 

bonne journée

2020-11-20 07:38 UTC, Tutt-J commented
Bonjour, il n'y a aucun fichier donc je ne pense pas que ce soit bon

2020-11-23 03:55 UTC, xsenikx commented
Bonjour,

je vais voir ça cette semaine, excusez-moi de mon absence durant ces 3
derniers jours.

Merci pour l'information bonne journée

Le ven. 20 nov. 2020 à 18:39, Tutt-J <notifications@github.com> a écrit :

> Bonjour, il n'y a aucun fichier donc je ne pense pas que ce soit bon
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xsenikx/P2-reservia/pull/9#issuecomment-730964028>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AROQUHBLKJCFSAPUE3ZW5ZDSQYMJNANCNFSM4T26AEEQ>
> .
>

2020-12-03 09:23 UTC, Tutt-J requested changes
File must be name "index.html"

2020-12-03 09:23 UTC, Tutt-J commented on index-structure.html
>  <head>
lang must be "fr"

2020-12-03 09:23 UTC, Tutt-J commented on index-structure.html
> +  <title>Reservia</title>
Missing meta description

2020-12-03 09:23 UTC, Tutt-J commented on index-structure.html
>    <div class="page">
In the body you just must have 
```
<header></header> 
<main></main>
<footer></footer>
```

2020-12-08 23:30 UTC, closed without merging